### ISSUE TITLE
toggle Graph

### ISSUE THREAD

**Issue by amaraabdallah** [formation-dwwm/graphcalc-js#7]
Mettre en place la fonctionnalité permettant de passer du mode de calcul au mode graph.

- [x] Placer un identifiant sur le canvas
- [x] Superposer affichage graph/calcul
- [x] Créer une classe CSS **hidden** qui cachera le canvas lorsque appliquée
- [x] Créer fonction JS **toggleMode** qui basculera la classe **hidden** sur le canvas
- [x] Lier le bouton `graph` avec la fonction `toggleMode`

**Comment by gatthias** [comment]
**Acceptance Criteria**

- [x] Bouton 'graph' visible sur le clavier
- [x] Au clic sur graph en mode calcul, l'utilisateur passe en mode graph
- [x] Au clic sur graph en mode graph, l'utilisateur passe en mode calcul
- [x] Le champ de saisie est réinitialisé au changement de mode
- [x] Le graph est redessiné lors du passage au mode graph
