### ISSUE TITLE
Saisir le calcul au clavier

### ISSUE THREAD

**Issue by amaraabdallah** [formation-dwwm/graphcalc-js#8]
- [x] Chaque touche physique du clavier doit afficher son équivalent sur l'écran

Définition des touches:
- [x] La touche entrée du clavier physique doit correspondre à la fonction égale.
- [x] Les touches numériques  0-9, ".", opérateurs ainsi que les parenthèses sont identiques à celles du clavier virtuel
- [x] La touche "p" correspond à la touche  "plus ou moins" du clavier virtuel
- [x] La touche "g" affiche ou masque le graphique ce qui  correspond à "Graph" sur clavier virtuel 
- [x]  La touche escape pour tout effacer correspond à "AC" sur clavier virtuel
- [x] La touche "BackSpace" pour  supprimer le dernier caractère correspond à "DEL" sur clavier virtuel

**Comment by natthamonng** [comment]
Nearly finished. Only the negative key (+-) to be done.

**Comment by amaraabdallah** [comment]
DONE,
